// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Implements the AI Insights lead assignment flow to analyze lead data and suggest high-potential leads for assignment.
 *
 * - suggestLeadAssignments - A function that suggests lead assignments based on AI analysis.
 * - SuggestLeadAssignmentsInput - The input type for the suggestLeadAssignments function.
 * - SuggestLeadAssignmentsOutput - The return type for the suggestLeadAssignments function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestLeadAssignmentsInputSchema = z.object({
  leadsData: z.string().describe('A stringified JSON array of lead objects, each containing relevant lead information such as contact details, lead score, interaction history, and other relevant attributes.'),
  salesTeamData: z.string().describe('A stringified JSON array of sales team member objects, each containing information such as skills, experience, current workload, and performance metrics.'),
});
export type SuggestLeadAssignmentsInput = z.infer<typeof SuggestLeadAssignmentsInputSchema>;

const SuggestLeadAssignmentsOutputSchema = z.object({
  suggestedAssignments: z.string().describe('A stringified JSON array of objects, each containing a lead ID and the ID of the suggested sales team member to assign the lead to, along with a confidence score for the assignment suggestion.'),
  analysisSummary: z.string().describe('A summary of the analysis performed to determine the lead assignments, including key factors considered and overall confidence level.'),
});
export type SuggestLeadAssignmentsOutput = z.infer<typeof SuggestLeadAssignmentsOutputSchema>;

export async function suggestLeadAssignments(input: SuggestLeadAssignmentsInput): Promise<SuggestLeadAssignmentsOutput> {
  return suggestLeadAssignmentsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestLeadAssignmentsPrompt',
  input: {schema: SuggestLeadAssignmentsInputSchema},
  output: {schema: SuggestLeadAssignmentsOutputSchema},
  prompt: `You are an AI assistant designed to analyze lead data and suggest optimal lead assignments to sales team members.

You are provided with the following data:

Leads Data: {{{leadsData}}}
Sales Team Data: {{{salesTeamData}}}

Based on this data, analyze the leads and sales team members to identify the best possible lead assignments.
Consider factors such as lead score, interaction history, sales team member skills, workload, and past performance.

Output a JSON array of suggested assignments, where each object contains the lead ID, the sales team member ID, and a confidence score (0-1) for the assignment suggestion.
Also, provide a summary of the analysis performed, including key factors considered and the overall confidence level in the suggested assignments.

Ensure that the output is a valid JSON string.
`,
});

const suggestLeadAssignmentsFlow = ai.defineFlow(
  {
    name: 'suggestLeadAssignmentsFlow',
    inputSchema: SuggestLeadAssignmentsInputSchema,
    outputSchema: SuggestLeadAssignmentsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
